version: "3.1"

language: en

pipeline:
- name: WhitespaceTokenizer

- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "bert-base-multilingual-cased"

- name: RegexFeaturizer

- name: LexicalSyntacticFeaturizer

- name: CountVectorsFeaturizer

- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4

- name: DIETClassifier
  epochs: 100

- name: EntitySynonymMapper

- name: DucklingEntityExtractor
  url: http://localhost:8000
  dimensions: ["time"]
  locale: "en_US"
  timezone: "Asia/Jakarta"

- name: ResponseSelector
  epochs: 100

- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

policies:
- name: RulePolicy
assistant_id: 20250430-231707-concave-genre
